src/Netnr.ResponseFramework/Netnr.ResponseFramework/Components/ButtonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;

namespace Netnr.ResponseFramework.ViewComponents
{
    public class ButtonViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            string current_url = "/" + RouteData.Values["controller"]?.ToString() + "/" + RouteData.Values["action"]?.ToString();

            //按钮列表
            var listBtn = new List<Domain.SysButton>();

            //根据路由反查页面对应的菜单
            //所有链接保持小写
            var moMenu = Func.Common.QuerySysMenuList(x => x.SmUrl == current_url.ToLower()).FirstOrDefault();
            if (moMenu != null)
            {
                //登录用户的角色信息
                var luri = Func.Common.LoginUserRoleInfo(HttpContext);
                if (luri != null && !string.IsNullOrWhiteSpace(luri.SrButtons))
                {
                    //角色配置的按钮
                    var joRole = JObject.Parse(luri.SrButtons);
                    //根据菜单ID取对应的按钮
                    string btns = joRole[moMenu.SmId].ToStringOrEmpty();
                    if (!string.IsNullOrWhiteSpace(btns))
                    {
                        var btnids = btns.Split(',').ToList();

                        //根据按钮ID取按钮
                        listBtn = Func.Common.QuerySysButtonList(x => btnids.Contains(x.SbId));
                    }
                }
            }

            return View(listBtn);
        }
    }
}

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_BaseViewPartial.cshtml
@model string
@if (Model != "0")
{
    <!--列表-->
    <div class="row">
        <div id="PGrid1" class="col-md-12">
            <div id="Grid1" class="loadingimg"></div>
        </div>
    </div>
}

<!--配置表格-->
<script src="/js/inlay/configtable.js" asp-append-version="true"></script>
<!--配置表单-->
<script src="/js/inlay/configform.js" asp-append-version="true"></script>
<!--搜索模块-->
<script src="/js/inlay/configquery.js" asp-append-version="true"></script>
<!--基础包-->
<script src="/js/inlay/baseviewpartial.js" asp-append-version="true"></script>
<!--引入页面JS-->
@{
    var jssrc = $"/js/{ViewContext.RouteData.Values["controller"].ToString().ToLower()}/{ViewContext.RouteData.Values["action"].ToString().ToLower()}.js";
    var jspath = GlobalTo.WebRootPath + jssrc;
    if (System.IO.File.Exists(jspath))
    {
        <script src='@jssrc' asp-append-version="true"></script>
    }
}
<script>
    //绑定数据
    setTimeout(z.FormAttrAjax, 0);
</script>

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge" />
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <title>@ViewData["Title"]</title>

    @await Html.PartialAsync("_QuotePartial", "bootstrap.css,fa.css,jquery.js,bootstrap.js,easyui,z.css,z.js")
</head>
<body>
    <div class="container-fluid">
        @await Component.InvokeAsync("Button")
        <div id="myBody">
            @RenderBody()
        </div>
    </div>
</body>
</html>

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_LoadingPartial.cshtml
<div id="LoadingMask" style="position: fixed; top: 0; left: 0; bottom: 0; right: 0; background-color: white; z-index: 9999; background-image:url('/images/loading.gif');background-repeat:no-repeat;background-position:48% 45%"></div>

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_QuotePartial.cshtml
@model string
@{
    var listQuote = Model.Split(',').ToList();
}
@foreach (var item in listQuote)
{
    switch (item)
    {
        case "fa.css":
            <link href="https://lib.baomitu.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
            break;

        case "jquery.js":
            <script src="https://lib.baomitu.com/jquery/1.12.4/jquery.min.js"></script>
            break;

        case "bootstrap.css":
            <link href="https://lib.baomitu.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
            break;

        case "bootstrap.js":
            <script src="https://lib.baomitu.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
            break;

        case "easyui":
            <link href="/lib/jquery-easyui/themes/metro/easyui.css" rel="stylesheet" asp-append-version="true" />
            <script src="/lib/jquery-easyui/jquery.easyui.min.js" asp-append-version="true"></script>
            break;

        case "ace.css":
            <link href="/lib/acenav/ace.min.css" rel="stylesheet" asp-append-version="true" />
            <link href="/lib/acenav/ace-skins.min.css" rel="stylesheet" asp-append-version="true" async />
            break;

        case "ace.js":
            <script src="/lib/acenav/ace.min.js" asp-append-version="true"></script>
            break;

        case "z.css":
            <link href="/css/z.css" rel="stylesheet" asp-append-version="true" />
            break;

        case "z.js":
            <script src="/js/z.js" asp-append-version="true"></script>
            break;

        case "init.js":
            <script src="/js/init.js" asp-append-version="true"></script>
            break;

    }
}