src/Netnr.ResponseFramework/Netnr.ResponseFramework/Components/FormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Netnr.Data;
using System.Linq;

namespace Netnr.ResponseFramework.Components
{
    public class FormViewComponent : ViewComponent
    {
        /// <summary>
        /// 模态框表单组件
        /// </summary>
        /// <param name="tablename">列配置表名</param>
        /// <param name="paneltitle">面板标题（有两个区域或以上时，英文逗号分隔）</param>
        /// <param name="modalsize">模态框大小 1小 2中 3大</param>
        /// <param name="index">表单ID后缀</param>
        /// <returns></returns>
        public IViewComponentResult Invoke(string tablename, string paneltitle = "", int modalsize = 3, int index = 1)
        {
            using (var db = new ContextBase())
            {
                //查询表对应的表单，排序，按区域分组
                var listCol = db.SysTableConfig.Where(x => x.TableName == tablename).OrderBy(x => x.FormOrder).ToList();

                var groupCol = listCol.GroupBy(x => x.FormArea.Value).ToList();

                //表名
                TempData["tablename"] = tablename;
                //ID索引
                TempData["index"] = index;
                //模态框大小
                TempData["modalsize"] = modalsize == 3 ? "modal-lg" : modalsize == 1 ? "modal-sm" : "";
                //多面板标题
                TempData["paneltitle"] = paneltitle.Split(',').ToList();

                return View(groupCol);
            }
        }
    }
}

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Controllers/RFController.cs
using System.ComponentModel;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Netnr.Data;
using Netnr.Func.ViewModel;
using System;
using System.Collections.Generic;
using Netnr.Domain;

namespace Netnr.ResponseFramework.Controllers
{
    /// <summary>
    /// 示例，请删除
    /// </summary>
    public class RFController : Controller
    {
        #region 表配置示例

        [Description("表配置示例页面")]
        public IActionResult Tce()
        {
            return View();
        }

        [Description("查询表配置示例")]
        public QueryDataOutputVM QueryTempExample(QueryDataInputVM ivm)
        {
            var ovm = new QueryDataOutputVM();
            using (var db = new ContextBase())
            {
                var query = db.TempExample;
                Func.Common.QueryJoin(query, ivm, db, ref ovm);
            }
            return ovm;
        }

        #endregion

        #region DataGrid示例页面

        [Description("DataGrid示例页面")]
        public IActionResult DataGrid()
        {
            return View();
        }

        [Description("查询表配置")]
        public QueryDataOutputVM QuerySysTableConfig(QueryDataInputVM ivm)
        {
            var ovm = new QueryDataOutputVM();
            using (var db = new ContextBase())
            {
                var query = db.SysTableConfig;
                Func.Common.QueryJoin(query, ivm, db, ref ovm);
            }
            return ovm;
        }

        #endregion

        #region TreeGrid示例页面

        [Description("TreeGrid示例页面")]
        public IActionResult TreeGrid(string id)
        {
            if (!string.IsNullOrWhiteSpace(id))
            {
                using (var db = new ContextBase())
                {
                    var query = from a in db.SysMenu
                                where a.SmPid == id
                                orderby a.SmOrder
                                select new
                                {
                                    a.SmId,
                                    a.SmPid,
                                    a.SmName,
                                    a.SmUrl,
                                    a.SmOrder,
                                    a.SmIcon,
                                    a.SmStatus,
                                    a.SmGroup,
                                    //查询是否有子集
                                    state = (from b in db.SysMenu where b.SmPid == a.SmId select b.SmId).Count() > 0 ? "closed" : "open"
                                };
                    var list = query.ToList();
                    return Content(list.ToJson());
                }
            }

            return View();
        }

        [Description("查询系统菜单")]
        public QueryDataOutputVM QuerySysMenu(QueryDataInputVM ivm)
        {
            var ovm = new QueryDataOutputVM();
            using (var db = new ContextBase())
            {
                var query = db.SysMenu;
                Func.Common.QueryJoin(query, ivm, db, ref ovm);
            }
            return ovm;
        }

        #endregion

        #region Grid多表格变动

        [Description("Grid多表格变动")]
        public IActionResult GridChange()
        {
            return View();
        }

        [Description("Grid多表格-主表")]
        public QueryDataOutputVM QueryGridChange1(QueryDataInputVM ivm)
        {
            var ovm = new QueryDataOutputVM();
            using (var db = new ContextBase())
            {
                var query = db.SysRole;
                Func.Common.QueryJoin(query, ivm, db, ref ovm);
            }
            return ovm;
        }

        [Description("Grid多表格-子表")]
        public QueryDataOutputVM QueryGridChange2(QueryDataInputVM ivm)
        {
            var ovm = new QueryDataOutputVM();
            using (var db = new ContextBase())
            {
                var query = db.SysUser;
                Func.Common.QueryJoin(query, ivm, db, ref ovm);
            }
            return ovm;
        }

        #endregion

        #region 生成多表单

        [Description("生成多表单")]
        public IActionResult BuildForms()
        {
            return View();
        }

        #endregion

        #region 静态表单示例页面

        [Description("静态表单示例页面")]
        public IActionResult Form()
        {
            return View();
        }

        #endregion

        #region 上传接口示例

        [Description("公共上传示例")]
        public IActionResult Upload()
        {
            return View();
        }

        #endregion

        #region 富文本

        [Description("嵌入富文本")]
        public IActionResult RichText()
        {
            return View();
        }

        #endregion

        #region Bulk Test，请手动修改 private 为 public 后测试

        [Description("批量新增")]
        private ActionResultVM BulkInsert()
        {
            var vm = new ActionResultVM();

            var list = new List<SysLog>();
            for (int i = 0; i < 50_000; i++)
            {
                var mo = new SysLog()
                {
                    LogId = Guid.NewGuid().ToString(),
                    LogAction = "/",
                    LogBrowserName = "Chrome",
                    LogCity = "重庆",
                    LogContent = "测试信息",
                    LogCreateTime = vm.startTime,
                    LogGroup = 1,
                    LogIp = "0.0.0.0",
                    LogSystemName = "Win10",
                    LogUrl = Request.Path,
                    SuName = "netnr",
                    SuNickname = "netnr",
                    LogRemark = "无"
                };
                list.Add(mo);
            }

            using (var db = new ContextBase())
            {
                db.SysLog.BulkInsert(list);

                db.BulkSaveChanges();

                vm.Set(ARTag.success);
            }

            return vm;
        }

        [Description("批量修改")]
        private ActionResultVM BulkUpdate()
        {
            var vm = new ActionResultVM();

            using (var db = new ContextBase())
            {
                var list = db.SysLog.OrderBy(x => x.LogCreateTime).Take(50_000).ToList();

                foreach (var item in list)
                {
                    item.LogRemark = Guid.NewGuid().ToString();
                }

                db.SysLog.BulkUpdate(list);

                db.BulkSaveChanges();

                vm.Set(ARTag.success);
            }

            return vm;
        }

        [Description("批量删除")]
        private ActionResultVM BulkDelete()
        {
            var vm = new ActionResultVM();

            using (var db = new ContextBase())
            {
                var list = db.SysLog.OrderBy(x => x.LogCreateTime).Take(50_000).ToList();

                db.SysLog.BulkDelete(list);

                db.BulkSaveChanges();

                vm.Set(ARTag.success);
            }

            return vm;
        }

        #endregion
    }
}

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/BuildForms.cshtml
@{
    ViewData["Title"] = "BuildForms";
}

<!--表单1，默认index=1 可不传-->
@await Component.InvokeAsync("Form", new { tablename = "TempExample", modalsize = 3, paneltitle = "面板一,面板二" })

<!--表单2-->
@await Component.InvokeAsync("Form", new { tablename = "SysButton", index = 2 })

<!--表单3-->
@await Component.InvokeAsync("Form", new { tablename = "SysUser", modalsize = 2, index = 3 })

<pre class="h4">
目前，在多表单的情况下，页面的表单、表格配置默认第一个，多表单、表格配置暂不支持；

页面上的配置主要是给用户使用，而用户一般不会使用该功能，意义不大；（如果有强烈需求，进群沟通交流）

而我们开发者应该在【系统设置-表配置】配置表单、表格；
</pre>

<button class="btn btn-primary" id="btn1">
    <i class="fa fa-plus"></i> 表单1
</button>
<button class="btn btn-primary" id="btn2">
    <i class="fa fa-plus"></i> 表单2
</button>
<button class="btn btn-primary" id="btn3">
    <i class="fa fa-plus"></i> 表单3
</button>

<script>
    $('#btn1').click(function () {
        $('#fv_modal_1').modal();
    });
    
    $('#btn2').click(function () {
        z.FormTitle({
            id: $('#fv_title_2'),
            icon: 0,
            title: '新增按钮'
        });
        $('#fv_modal_2').modal();
    });

    $('#btn3').click(function () {
        z.FormTitle({
            id: $('#fv_title_3'),
            icon: 0,
            title: '新增用户'
        });
        $('#fv_modal_3').modal();
    });
</script>

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/DataGrid.cshtml
@{
    ViewData["Title"] = "DataGrid";
}

<!--快捷查询-->
<div class="row">
    <div class="col-md-2 col-sm-4 col-xs-6 mb5">
        <div class="input-group">
            <span class="input-group-addon">虚表</span>
            <select class="form-control" id="query_tablename">
                <option value="">全部</option>
                <option>SysTableConfig</option>
                <option>SysUser</option>
                <option>SysRole</option>
                <option>SysLog</option>
                <option disabled>示例数据，没列完</option>
            </select>
        </div>
    </div>
    <div class="col-md-4 col-sm-8 col-xs-6 mb5">
        <div class="input-group">
            <span class="input-group-addon">列键</span>
            <input class="form-control" id="query_colfield" placeholder="模糊搜索表字段名" />
            <span class="input-group-btn">
                <button class="btn btn-primary" id="btnSearch">搜索</button>
            </span>
        </div>
    </div>
</div>

<partial name="_BaseViewPartial" />

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/GridChange.cshtml
@{
    ViewData["Title"] = "Grid多表格变动";
}

<!--列表-->
<div class="row">
    <div class="col-md-5">
        <div id="PGrid1" class="gridedit">
            <div id="Grid1" class="loadingimg"></div>
        </div>
    </div>
    <div class="col-md-7">
        <div id="PGrid2" class="gridedit">
            <div id="Grid2" class="loadingimg"></div>
        </div>
    </div>
</div>

<!--搜索模块-->
<script src="/js/inlay/configquery.js" asp-append-version="true"></script>

<script src="/js/rf/gridchange.js" asp-append-version="true"></script>

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/GridQuery.cshtml
@{
    ViewData["Title"] = "GridQuery";
}

<h2>GridQuery</h2>

<!--列表-->
<div class="row">
    <div class="col-md-12">
        <div id="PGrid1" class="gridedit">
            <div id="Grid1" class="loadingimg"></div>
        </div>
    </div>
</div>

<script>
    z.TableName = "SysTableConfig";

    //载入
    var gd1 = z.Grid();
    gd1.url = "/RF/HttpGridQuery?tableName=" + z.TableName;
    gd1.pageSize = 10;
    gd1.multiSort = true;
    gd1.sortName = "TableName,ColOrder";
    gd1.sortOrder = "asc,asc";
    gd1.onLoadSuccess = function () {
        gd1.QueryMark();
    }
    gd1.load();
</script>

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/RichText.cshtml
@{
    ViewData["Title"] = "富文本";
}

<!--模态 表单-->
<div class="modal fade modalautoheight" id="fv_modal_1" role="dialog" data-backdrop="static">
    <div class='modal-dialog modal-lg modal-full'>
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="fv_title_1">
                    <i class="fa fa-plus blue"></i><span>表单标题</span><em>✶ 为必填</em>
                </h4>
            </div>

            <div class="modal-body">
                <form class="form-horizontal formui" id="fv_form_1">
                    <div class="row">

                        <div class='col-md-12 col-sm-12'>
                            <div class="form-group">
                                <label class='control-label'>标题</label>
                                <div>
                                    <input type='text' id="SbBtnId" name="SbBtnId" class="form-control" data-type="text" data-query="0" data-url="" maxlength="20" />
                                </div>
                            </div>
                        </div>
                        <div class='col-md-12 col-sm-12'>
                            <div class="form-group">
                                <label class='control-label required'>内容</label>
                                <div>
                                    <textarea id="txtRich" name="txtRich" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="fv_save_1" type="button" class="btn btn-primary"><span class="fa fa-save"></span>&nbsp;保存 触发必填验证</button>
            </div>
        </div>
    </div>
</div>

<script src="https://lib.baomitu.com/ckeditor/4.11.4/ckeditor.js"></script>

<partial name="_BaseViewPartial" />

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/Tce.cshtml
@{
    ViewData["Title"] = "表配置示例";
}

@await Component.InvokeAsync("Form", new { tablename = "TempExample", modalsize = 3, paneltitle = "面板一,面板二" })

<partial name="_BaseViewPartial" />

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/TreeGrid.cshtml
@{
    ViewData["Title"] = "TreeGrid";
}

<partial name="_BaseViewPartial" />

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/RF/Upload.cshtml
@{
    ViewData["Title"] = "上传";
}

<!--模态 表单-->
<div class="modal fade modalautoheight" id="fv_modal_1" role="dialog" data-backdrop="static">
    <div class='modal-dialog modal-lg'>
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="fv_title_1">
                    <i class="fa fa-plus blue"></i><span>表单标题</span><em>✶ 为必填</em>
                </h4>
            </div>

            <div class="modal-body">
                <form class="form-horizontal formui" id="fv_form_1">
                    <div class="row">

                        <div class='col-md-6 col-sm-6 '>
                            <div class="form-group">
                                <label class='control-label required'>&#x6309;&#x94AE;&#x6587;&#x672C;</label>
                                <div>
                                    <input type='text' id="SbBtnText" name="SbBtnText" class="form-control" data-type="text" data-query="0" data-url="" maxlength="20" />
                                </div>
                            </div>
                        </div>
                        <div class='col-md-6 col-sm-6 '>
                            <div class="form-group">
                                <label class='control-label '>&#x4E0A;&#x7EA7;&#x6309;&#x94AE;</label>
                                <div>
                                    <input type='text' id="SbPid" name="SbPid" class="form-control" data-type="combotree" data-query="0" data-url="/Common/QueryButtonTree" placeholder="&#x65E0;&#x4E0A;&#x7EA7;&#x6309;&#x94AE;&#x4E0D;&#x586B;" maxlength="50" />
                                </div>
                            </div>
                        </div>
                        <div class='col-md-6 col-sm-6 hidden'>
                            <div class="form-group">
                                <label class='control-label '>SbId</label>
                                <div>
                                    <input type='text' id="SbId" name="SbId" class="form-control" data-type="text" data-query="0" data-url="" maxlength="50" />
                                </div>
                            </div>
                        </div>
                        <div class='col-md-12 col-sm-6 '>
                            <div class="form-group">
                                <label class='control-label required'>文件上传</label>
                                <div>
                                    <input type='file' id="txtFile" class="form-control" />
                                    <input type="hidden" id="hid_txtFile" name="txtFile" />
                                    <p class="help-block">文件最大2M，支持格式 jpg、png、gif</p>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-6 col-sm-6 '>
                            <div class="form-group">
                                <label class='control-label '>&#x6309;&#x94AE;&#x6392;&#x5E8F;</label>
                                <div>
                                    <input type='text' id="SbBtnOrder" name="SbBtnOrder" class="form-control" data-type="text" data-query="0" data-url="" placeholder="&#x5347;&#x5E8F;" maxlength="10" />
                                </div>
                            </div>
                        </div>
                        <div class='col-md-6 col-sm-6 '>
                            <div class="form-group">
                                <label class='control-label'>&#x6309;&#x94AE;ID</label>
                                <div>
                                    <input type='text' id="SbBtnId" name="SbBtnId" class="form-control" data-type="text" data-query="0" data-url="" placeholder="m_ &#x5F00;&#x5934;" maxlength="50" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="fv_save_1" type="button" class="btn btn-primary"><span class="fa fa-save"></span>&nbsp;保存 触发必填验证</button>
            </div>
        </div>
    </div>
</div>

<partial name="_BaseViewPartial" />